# Generated by Django 3.2.13 on 2023-09-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('intensidade', models.CharField(choices=[('P', 'Pouca'), ('M', 'Media'), ('I', 'Intensa')], max_length=1)),
                ('melhoria', models.CharField(max_length=50)),
                ('como_fazer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Principios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('prioridade', models.CharField(max_length=50)),
                ('data_criacao', models.DateField()),
                ('criador', models.CharField(max_length=50)),
            ],
        ),
    ]
